### ISSUE TITLE
Empty uri passed to Mongo

### ISSUE THREAD

**Issue by ArVan** [willhuang85/skipper-gridfs#18]
Hi. I'm trying to implement auto upload to gridFS and encountered a problem. Whenever uploading a file I get this error from Mongo:

```
Error: URL must be in the format mongodb://user:pass@host:port/dbname
    at Error (native)
    at exports.parse (/nodejs/rop-db/node_modules/skipper-gridfs/node_modules/mongodb/lib/mongodb/connection/url_parser.js:15:11)
    at Function.MongoClient.connect (/nodejs/rop-db/node_modules/skipper-gridfs/node_modules/mongodb/lib/mongodb/mongo_client.js:164:16)
    at Writable.onFile (/nodejs/rop-db/node_modules/skipper-gridfs/index.js:205:29)
```

My code looks like this:

``` javascript
req.file('user-avatar').upload({
            adapter: require('skipper-gridfs'),
            uri: sails.config.connections.mongo.url
        }, function (err, filesUploaded) {
            ...
        });
```

So I digged deeper and so the following:
In `skipper-gridfs/index.js:205`
![screen shot 2015-07-23 at 10 41 46 am](https://cloud.githubusercontent.com/assets/3704570/8844560/1bbfb100-311f-11e5-995c-4fbf5008b25f.png)
So the `globalOpts.uri` is empty.
But a few lines up where `options = _.defaults(options, globalOpts);` I see
![screen shot 2015-07-23 at 10 43 55 am](https://cloud.githubusercontent.com/assets/3704570/8844589/651367f2-311f-11e5-854e-06db372136b2.png)
Where the uri is correct.

Don't know what happens before this code but it seems `MongoClient.connect` should receive `options.uri` instead?

**Comment by ArVan** [comment]
Hmm.. the error vanished when I attached bucket to the uri. Is it mandatory?

**Comment by willhuang85** [comment]
Currently the code requires a bucket. I'll update the code to fix that.
