### ISSUE TITLE
Cannot find module '../build/Release/bson'

### ISSUE THREAD

**Issue by japel** [willhuang85/skipper-gridfs#23]
Using the latest published version of skipper-gridfs I'm getting the following error when installing:

``` javascript
> bson@0.2.22 install /test/node_modules/skipper-gridfs/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/test/node_modules/skipper-gridfs/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
bson.target.mk:88: recipe for target 'Release/obj.target/bson/ext/bson.o' failed
make: Leaving directory '/test/node_modules/skipper-gridfs/node_modules/bson/build'
```

And when I lift sails, I get the following warning/error:

``` javascript
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

this has most probably something to do with the mongodb version used in the published version which is: "^1.4.18"

When I try the master branch, which has "mongodb": "~2.0", there are no installation errors anymore and sails lifts without warnings/errors.

would it be possible to publish a version with updated dependencies?

best regards

japel

**Comment by mblais29** [comment]
Hi Japel,

This worked for me

Go to the file (in your project):
**_'node_modules/mongoose/node_modules/mongodb/node_modules/bson/ext/index.js'_**
and change
`bson = require('../build/Release/bson');`
to
`bson = require('bson');`
