### ISSUE TITLE
skipper-gridfs isn't storing chunks with node v14

### ISSUE THREAD

**Issue by jmelich** [willhuang85/skipper-gridfs#40]
After upgrade node to v14 seems right given whenDone() is triggered with NO errors and printing uploaded file callback variable values seems normal even have a file descriptor id. The problem comes when I try to download the uploaded file, it's metadata exists but file itself no, and navigator downloads an empty file of 17kb always mantaining original file name.

Problem comes since I upgraded node to v14 from v12 for an Angular 9 app compatibility(now I'm considering to dockerize to avoid this situation, but I need to fix file uploading until it). The situation is I can download with success uploaded files when node was v12, but not uploaded files with v14. When I try to get a file the error is the following: 
`Error: FileNotFound: file 6a5a6cda-8669-4af1-8b74-c13ecc5ed178.png was not found`

I tried all skipper-gridfs versions in combination with node v14 and the same is happening.

Node version: v14.4.0

package.json have the following:
```
    "sails-mongo": "^1.2.0",
    "sails-mysql": "1.0.1",
    "skipper": "^0.9.0-4",
    "skipper-gridfs": "^1.0.2"
```

**Comment by dmedina2015** [comment]
I made some changes in the code and now it is working properly with node 14+. It is contained in PRs #45 and #44 that are not yet approved.
In the meanwhile, you can use [my fork](https://github.com/dmedina2015/skipper-gridfs), where these modifications are already in master branch.

**Comment by jmelich** [comment]
@dmedina2015 thanks for your great work but we've turned into amazon-s3 adapter as a workaround, after that we thought it was better place for our business files. Even that I'm going to close this Issue and try the new code when PR will be merged.

Thanks you once again ;)
